# railway.toml

# This section configures the build process.
# We're telling Railway to use the Dockerfile in your project.
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

# This section configures the deployment and runtime behavior.
[deploy]
# Defines how Railway should handle failures.
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 # Attempt to restart up to 10 times on failure

# Optional: This section can define files and directories to watch.
# Changes to these files can trigger automatic rebuilds on Railway if connected to a Git repo.
[watch]
watchPatterns = [
    "*.go",
    "go.mod",
    "go.sum",
    "schema.sql",
    "tmpl/*",
    "static/*",
    "Dockerfile",
    "railway.toml"
]

# This section configures health checks for your service.
# Railway will periodically send an HTTP GET request to this path.
# If it doesn't receive a 2xx response within the timeout,
# it will consider the service unhealthy and may restart it.
[healthcheck]
path = "/healthz" # Updated health check path
timeout = 10 # seconds
interval = 30 # seconds
retries = 3 