# railway.toml

# This section configures the build process.
# We're telling Railway to use the Dockerfile in your project.
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

# This section configures the deployment and runtime behavior.
[deploy]
# startCommand has been removed. Railway will use the CMD and ENTRYPOINT from the Dockerfile.
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Optional: This section can define files and directories to watch.
# Changes to these files can trigger automatic rebuilds on Railway if connected to a Git repo.
[watch]
watchPatterns = [
    "*.go",
    "go.mod",
    "go.sum",
    "schema.sql",
    "tmpl/*",
    "static/*",
    "Dockerfile",
    "railway.toml"
]

# This section defines health checks for your application.
# Railway uses these to determine if your deployment is healthy.
[healthcheck]
# HTTP path for the health check.
path = "/healthz"
# How often (in seconds) to perform the health check.
interval = "30s"
# How long (in seconds) to wait for a response before timing out.
timeout = "5s"
# Number of consecutive failed health checks before marking the deployment as unhealthy.
retries = 3 